package panel

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/nigelteosw/eggy/internal/channel/webchat"
	"github.com/nigelteosw/eggy/internal/core/destination"
	"github.com/nigelteosw/eggy/internal/core/events"
	"github.com/nigelteosw/eggy/internal/ports"
	sqlitestore "github.com/nigelteosw/eggy/internal/storage/sqlite"
)

func newTestMemoryStore(t *testing.T) *sqlitestore.Store {
	t.Helper()
	store, err := sqlitestore.Open(filepath.Join(t.TempDir(), "eggy.db"), 100)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = store.Close() })
	return store
}

func withPathValue(request *http.Request, key, value string) *http.Request {
	request.SetPathValue(key, value)
	return request
}

func TestThreadListReturnsOnlyWebThreadsMostRecentlyActiveFirst(t *testing.T) {
	memory := newTestMemoryStore(t)
	base := time.Now()
	if _, err := memory.CreateThread(asOwner(), "thread-1", "web", base); err != nil {
		t.Fatal(err)
	}
	if _, err := memory.CreateThread(asOwner(), "thread-2", "web", base.Add(time.Minute)); err != nil {
		t.Fatal(err)
	}
	if _, err := memory.CreateThread(asOwner(), "telegram", "telegram", base); err != nil {
		t.Fatal(err)
	}
	handler := newThreadListHandler(memory)

	request := ownerRequest(http.MethodGet, "/api/chat/threads", nil)
	response := httptest.NewRecorder()
	handler(response, request)

	var decoded webResult
	if err := json.Unmarshal(response.Body.Bytes(), &decoded); err != nil {
		t.Fatal(err)
	}
	if len(decoded.TableRows) != 2 || decoded.TableRows[0][0] != "thread-2" || decoded.TableRows[1][0] != "thread-1" {
		t.Fatalf("rows=%#v", decoded.TableRows)
	}
}

func TestThreadCreateReturnsANewUntitledThreadID(t *testing.T) {
	memory := newTestMemoryStore(t)
	handler := newThreadCreateHandler(memory, time.Now)

	request := ownerRequest(http.MethodPost, "/api/chat/threads", nil)
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusCreated {
		t.Fatalf("status=%d body=%s", response.Code, response.Body.String())
	}
	var decoded struct {
		ID string `json:"id"`
	}
	if err := json.Unmarshal(response.Body.Bytes(), &decoded); err != nil {
		t.Fatal(err)
	}
	if decoded.ID == "" {
		t.Fatal("expected a non-empty thread ID")
	}
	if _, found, err := memory.GetThread(asOwner(), decoded.ID); err != nil || !found {
		t.Fatalf("thread not persisted: found=%v err=%v", found, err)
	}
}

func TestThreadRenameOverwritesAnAutoGeneratedTitle(t *testing.T) {
	memory := newTestMemoryStore(t)
	if _, err := memory.CreateThread(asOwner(), "thread-1", "web", time.Now()); err != nil {
		t.Fatal(err)
	}
	if err := memory.SetThreadTitle(asOwner(), "thread-1", "auto title"); err != nil {
		t.Fatal(err)
	}
	handler := newThreadRenameHandler(memory)

	request := withPathValue(ownerRequest(http.MethodPatch, "/api/chat/threads/thread-1", strings.NewReader(`{"title":"  Groceries  "}`)), "id", "thread-1")
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusOK {
		t.Fatalf("status=%d body=%s", response.Code, response.Body.String())
	}
	thread, _, err := memory.GetThread(asOwner(), "thread-1")
	if err != nil {
		t.Fatal(err)
	}
	if thread.Title != "Groceries" {
		t.Fatalf("title=%q", thread.Title)
	}
}

func TestThreadRenameRejectsABlankTitle(t *testing.T) {
	memory := newTestMemoryStore(t)
	if _, err := memory.CreateThread(asOwner(), "thread-1", "web", time.Now()); err != nil {
		t.Fatal(err)
	}
	handler := newThreadRenameHandler(memory)

	request := withPathValue(ownerRequest(http.MethodPatch, "/api/chat/threads/thread-1", strings.NewReader(`{"title":"   "}`)), "id", "thread-1")
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusBadRequest {
		t.Fatalf("status=%d", response.Code)
	}
}

func TestThreadRenameReturns404ForAnUnknownThread(t *testing.T) {
	memory := newTestMemoryStore(t)
	handler := newThreadRenameHandler(memory)

	request := withPathValue(ownerRequest(http.MethodPatch, "/api/chat/threads/missing", strings.NewReader(`{"title":"x"}`)), "id", "missing")
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusNotFound {
		t.Fatalf("status=%d", response.Code)
	}
}

func TestThreadDeleteRemovesTheThreadAndItsMessages(t *testing.T) {
	memory := newTestMemoryStore(t)
	if _, err := memory.CreateThread(asOwner(), "thread-1", "web", time.Now()); err != nil {
		t.Fatal(err)
	}
	if err := memory.WriteMessage(asOwner(), ports.StoredMessage{
		ConversationID: "thread-1", Role: ports.RoleUser, Content: "hi", Source: "web", CreatedAt: time.Now(),
	}); err != nil {
		t.Fatal(err)
	}
	handler := newThreadDeleteHandler(memory)

	request := withPathValue(ownerRequest(http.MethodDelete, "/api/chat/threads/thread-1", nil), "id", "thread-1")
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusOK {
		t.Fatalf("status=%d body=%s", response.Code, response.Body.String())
	}
	if _, found, err := memory.GetThread(asOwner(), "thread-1"); err != nil || found {
		t.Fatalf("thread still present: found=%v err=%v", found, err)
	}
	messages, err := memory.RecentMessages(asOwner(), "thread-1", 10)
	if err != nil {
		t.Fatal(err)
	}
	if len(messages) != 0 {
		t.Fatalf("messages=%#v", messages)
	}
}

func TestThreadDeleteRefusesAThreadWithAWorkspaceAttached(t *testing.T) {
	memory := newTestMemoryStore(t)
	if _, err := memory.CreateThread(asOwner(), "thread-1", "web", time.Now()); err != nil {
		t.Fatal(err)
	}
	if err := memory.AttachWorkspace(asOwner(), "thread-1", "web", "repo", "/tmp/checkout", time.Now()); err != nil {
		t.Fatal(err)
	}
	handler := newThreadDeleteHandler(memory)

	request := withPathValue(ownerRequest(http.MethodDelete, "/api/chat/threads/thread-1", nil), "id", "thread-1")
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusConflict {
		t.Fatalf("status=%d body=%s", response.Code, response.Body.String())
	}
	if _, found, err := memory.GetThread(asOwner(), "thread-1"); err != nil || !found {
		t.Fatalf("thread was deleted anyway: found=%v err=%v", found, err)
	}
}

func TestThreadDeleteReturns404ForAnUnknownThread(t *testing.T) {
	memory := newTestMemoryStore(t)
	handler := newThreadDeleteHandler(memory)

	request := withPathValue(ownerRequest(http.MethodDelete, "/api/chat/threads/missing", nil), "id", "missing")
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusNotFound {
		t.Fatalf("status=%d", response.Code)
	}
}

func TestThreadHistoryReturnsThatThreadsRecentMessagesAsTableRows(t *testing.T) {
	memory := newTestMemoryStore(t)
	if _, err := memory.CreateThread(asOwner(), "thread-1", "web", time.Now()); err != nil {
		t.Fatal(err)
	}
	if err := memory.WriteMessage(asOwner(), ports.StoredMessage{
		ConversationID: "thread-1", Role: ports.RoleUser, Content: "hi", Source: "web", CreatedAt: time.Now(),
	}); err != nil {
		t.Fatal(err)
	}
	if err := memory.WriteMessage(asOwner(), ports.StoredMessage{
		ConversationID: "thread-1", Role: ports.RoleAssistant, Content: "hello!", Source: "web", CreatedAt: time.Now().Add(time.Second),
	}); err != nil {
		t.Fatal(err)
	}
	if err := memory.WriteMessage(asOwner(), ports.StoredMessage{
		ConversationID: "other-thread", Role: ports.RoleUser, Content: "not this one", Source: "web", CreatedAt: time.Now(),
	}); err != nil {
		t.Fatal(err)
	}
	handler := newThreadHistoryHandler(memory, memory)

	request := withPathValue(ownerRequest(http.MethodGet, "/api/chat/threads/thread-1/history", nil), "id", "thread-1")
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusOK {
		t.Fatalf("status=%d body=%s", response.Code, response.Body.String())
	}
	var decoded webResult
	if err := json.Unmarshal(response.Body.Bytes(), &decoded); err != nil {
		t.Fatal(err)
	}
	if len(decoded.TableRows) != 2 || decoded.TableRows[0][0] != "user" || decoded.TableRows[0][1] != "hi" {
		t.Fatalf("rows=%#v", decoded.TableRows)
	}
	if decoded.TableRows[1][0] != "assistant" || decoded.TableRows[1][1] != "hello!" {
		t.Fatalf("rows=%#v", decoded.TableRows)
	}
}

func TestThreadHistoryReturns404ForAnUnknownThread(t *testing.T) {
	memory := newTestMemoryStore(t)
	handler := newThreadHistoryHandler(memory, memory)

	request := withPathValue(ownerRequest(http.MethodGet, "/api/chat/threads/missing/history", nil), "id", "missing")
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusNotFound {
		t.Fatalf("status=%d", response.Code)
	}
}

func TestThreadSendEnqueuesAMessageEventScopedToTheThread(t *testing.T) {
	memory := newTestMemoryStore(t)
	if _, err := memory.CreateThread(asOwner(), "thread-1", "web", time.Now()); err != nil {
		t.Fatal(err)
	}
	var got events.Event
	enqueue := func(_ context.Context, event events.Event) error {
		got = event
		return nil
	}
	handler := newThreadSendHandler(enqueue, memory)

	request := withPathValue(ownerRequest(http.MethodPost, "/api/chat/threads/thread-1/send", strings.NewReader(`{"text":"hello Eggy"}`)), "id", "thread-1")
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusAccepted {
		t.Fatalf("status=%d body=%s", response.Code, response.Body.String())
	}
	if got.Type != events.TypeMessage || got.Source != "web" {
		t.Fatalf("event=%#v", got)
	}
	if got.Destination.Kind != destination.Web || got.Destination.ThreadID != "thread-1" {
		t.Fatalf("Destination=%#v, want the thread ID", got.Destination)
	}
	if got.Owner != "42" {
		t.Fatalf("Owner=%q, want the authenticated session's account (Dispatcher.Handle rejects anything else)", got.Owner)
	}
	if got.ID == "" || got.CorrelationID != got.ID {
		t.Fatalf("ID=%q CorrelationID=%q, want both set and equal, matching Telegram's event shape", got.ID, got.CorrelationID)
	}
	var message events.Message
	if err := json.Unmarshal(got.Payload, &message); err != nil {
		t.Fatal(err)
	}
	if message.Text != "hello Eggy" {
		t.Fatalf("message=%#v", message)
	}
}

func TestThreadSendCarriesAQuoteThroughToTheEvent(t *testing.T) {
	memory := newTestMemoryStore(t)
	if _, err := memory.CreateThread(asOwner(), "thread-1", "web", time.Now()); err != nil {
		t.Fatal(err)
	}
	var got events.Event
	handler := newThreadSendHandler(func(_ context.Context, event events.Event) error { got = event; return nil }, memory)

	body := `{"text":"why?","quote":{"text":"quarterly basis","own_message":true}}`
	request := withPathValue(ownerRequest(http.MethodPost, "/api/chat/threads/thread-1/send", strings.NewReader(body)), "id", "thread-1")
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusAccepted {
		t.Fatalf("status=%d body=%s", response.Code, response.Body.String())
	}
	var message events.Message
	if err := json.Unmarshal(got.Payload, &message); err != nil {
		t.Fatal(err)
	}
	if message.Text != "why?" || message.Quote == nil || message.Quote.Text != "quarterly basis" || !message.Quote.OwnMessage {
		t.Fatalf("message=%#v", message)
	}

	// A blank quote is what a client sends when nothing was highlighted; it
	// must not reach the model as an empty "[Replying to: ""]".
	request = withPathValue(ownerRequest(http.MethodPost, "/api/chat/threads/thread-1/send", strings.NewReader(`{"text":"hi","quote":{"text":" "}}`)), "id", "thread-1")
	handler(httptest.NewRecorder(), request)
	var plain events.Message
	if err := json.Unmarshal(got.Payload, &plain); err != nil {
		t.Fatal(err)
	}
	if plain.Quote != nil {
		t.Fatalf("quote=%#v, want none", plain.Quote)
	}
}

func TestThreadSendReturns404ForAnUnknownThread(t *testing.T) {
	memory := newTestMemoryStore(t)
	handler := newThreadSendHandler(func(context.Context, events.Event) error { return nil }, memory)

	request := withPathValue(ownerRequest(http.MethodPost, "/api/chat/threads/missing/send", strings.NewReader(`{"text":"hi"}`)), "id", "missing")
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusNotFound {
		t.Fatalf("status=%d", response.Code)
	}
}

func TestThreadSendRejectsEmptyText(t *testing.T) {
	memory := newTestMemoryStore(t)
	if _, err := memory.CreateThread(asOwner(), "thread-1", "web", time.Now()); err != nil {
		t.Fatal(err)
	}
	handler := newThreadSendHandler(func(context.Context, events.Event) error { return nil }, memory)

	request := withPathValue(ownerRequest(http.MethodPost, "/api/chat/threads/thread-1/send", strings.NewReader(`{"text":""}`)), "id", "thread-1")
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusBadRequest {
		t.Fatalf("status=%d", response.Code)
	}
}

func TestThreadSendRejectsInvalidBody(t *testing.T) {
	memory := newTestMemoryStore(t)
	if _, err := memory.CreateThread(asOwner(), "thread-1", "web", time.Now()); err != nil {
		t.Fatal(err)
	}
	handler := newThreadSendHandler(func(context.Context, events.Event) error { return nil }, memory)

	request := withPathValue(ownerRequest(http.MethodPost, "/api/chat/threads/thread-1/send", strings.NewReader(`not json`)), "id", "thread-1")
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusBadRequest {
		t.Fatalf("status=%d", response.Code)
	}
}

func TestThreadSendReturns500WhenEnqueueFails(t *testing.T) {
	memory := newTestMemoryStore(t)
	if _, err := memory.CreateThread(asOwner(), "thread-1", "web", time.Now()); err != nil {
		t.Fatal(err)
	}
	handler := newThreadSendHandler(func(context.Context, events.Event) error { return errors.New("queue full") }, memory)

	request := withPathValue(ownerRequest(http.MethodPost, "/api/chat/threads/thread-1/send", strings.NewReader(`{"text":"hi"}`)), "id", "thread-1")
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusInternalServerError {
		t.Fatalf("status=%d", response.Code)
	}
}

func TestThreadStreamDeliversABroadcastEventScopedToThatThreadAsSSE(t *testing.T) {
	memory := newTestMemoryStore(t)
	if _, err := memory.CreateThread(asOwner(), "thread-1", "web", time.Now()); err != nil {
		t.Fatal(err)
	}
	hub := webchat.NewHub()
	handler := newThreadStreamHandler(hub, memory, nil)

	ctx, cancel := context.WithTimeout(asOwner(), 200*time.Millisecond)
	defer cancel()
	request := withPathValue(ownerRequest(http.MethodGet, "/api/chat/threads/thread-1/stream", nil).WithContext(ctx), "id", "thread-1")
	response := httptest.NewRecorder()

	done := make(chan struct{})
	go func() {
		handler(response, request)
		close(done)
	}()

	time.Sleep(20 * time.Millisecond) // let the handler register with the hub
	hub.Broadcast("42", "thread-1", webchat.Event{Kind: webchat.EventMessage, ID: "1", Text: "hello"})
	hub.Broadcast("42", "other-thread", webchat.Event{Kind: webchat.EventMessage, ID: "2", Text: "not this thread"})
	hub.Broadcast("someone-else", "thread-1", webchat.Event{Kind: webchat.EventMessage, ID: "3", Text: "not this account"})

	<-done
	body := response.Body.String()
	if !strings.Contains(body, "event: message") || !strings.Contains(body, `"text":"hello"`) {
		t.Fatalf("body=%q", body)
	}
	if strings.Contains(body, "not this thread") || strings.Contains(body, "not this account") {
		t.Fatalf("body=%q, want no events from another thread or account", body)
	}
}

func TestThreadStreamSetsSSEHeaders(t *testing.T) {
	memory := newTestMemoryStore(t)
	if _, err := memory.CreateThread(asOwner(), "thread-1", "web", time.Now()); err != nil {
		t.Fatal(err)
	}
	hub := webchat.NewHub()
	handler := newThreadStreamHandler(hub, memory, nil)

	ctx, cancel := context.WithTimeout(asOwner(), 20*time.Millisecond)
	defer cancel()
	request := withPathValue(ownerRequest(http.MethodGet, "/api/chat/threads/thread-1/stream", nil).WithContext(ctx), "id", "thread-1")
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Header().Get("Content-Type") != "text/event-stream" {
		t.Fatalf("Content-Type=%q", response.Header().Get("Content-Type"))
	}
}

func TestThreadStreamReturns404ForAnUnknownThread(t *testing.T) {
	memory := newTestMemoryStore(t)
	hub := webchat.NewHub()
	handler := newThreadStreamHandler(hub, memory, nil)

	request := withPathValue(ownerRequest(http.MethodGet, "/api/chat/threads/missing/stream", nil), "id", "missing")
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusNotFound {
		t.Fatalf("status=%d", response.Code)
	}
}

func TestChatApproveEnqueuesAnApprovalDecisionEventWithTheOwnerSet(t *testing.T) {
	var got events.Event
	enqueue := func(_ context.Context, event events.Event) error {
		got = event
		return nil
	}
	handler := newChatApproveHandler(enqueue)

	request := ownerRequest(http.MethodPost, "/api/chat/approve", strings.NewReader(`{"approval_id":"approval-1","approved":true}`))
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusAccepted {
		t.Fatalf("status=%d body=%s", response.Code, response.Body.String())
	}
	if got.Type != events.TypeApproval || got.Owner != "42" {
		t.Fatalf("event=%#v", got)
	}
	var decision events.ApprovalDecision
	if err := json.Unmarshal(got.Payload, &decision); err != nil {
		t.Fatal(err)
	}
	if decision.ApprovalID != "approval-1" || !decision.Approved {
		t.Fatalf("decision=%#v", decision)
	}
	if decision.MessageID != "" {
		t.Fatalf("expected empty Telegram-only fields, decision=%#v", decision)
	}
}

func TestChatApproveRejectsMissingApprovalID(t *testing.T) {
	handler := newChatApproveHandler(func(context.Context, events.Event) error { return nil })

	request := ownerRequest(http.MethodPost, "/api/chat/approve", strings.NewReader(`{"approved":true}`))
	response := httptest.NewRecorder()
	handler(response, request)

	if response.Code != http.StatusBadRequest {
		t.Fatalf("status=%d", response.Code)
	}
}
